package persistencia;
// Generated 14 jun. 2022 12:36:32 by Hibernate Tools 5.4.21.Final

/**
 * Anexar generated by hbm2java
 */
public class Anexar implements java.io.Serializable {

	private Integer idAnexado;
	private Alumno alumno;
	private Convenio convenio;
	private Practica practica;

	public Anexar() {
	}

	public Anexar(Alumno alumno, Convenio convenio, Practica practica) {
		this.alumno = alumno;
		this.convenio = convenio;
		this.practica = practica;
	}

	public Integer getIdAnexado() {
		return this.idAnexado;
	}

	public void setIdAnexado(Integer idAnexado) {
		this.idAnexado = idAnexado;
	}

	public Alumno getAlumno() {
		return this.alumno;
	}

	public void setAlumno(Alumno alumno) {
		this.alumno = alumno;
	}

	public Convenio getConvenio() {
		return this.convenio;
	}

	public void setConvenio(Convenio convenio) {
		this.convenio = convenio;
	}

	public Practica getPractica() {
		return this.practica;
	}

	public void setPractica(Practica practica) {
		this.practica = practica;
	}
	@Override
    public String toString() {
        return "- " + alumno + "         ----       " + convenio.getEmpresa().getNombreEmpresa() + "                " + convenio.getIdConvenio();
    }
}
