package persistencia;
// Generated 2 jun. 2022 16:39:34 by Hibernate Tools 5.4.32.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Convenio generated by hbm2java
 */
public class Convenio implements java.io.Serializable {

	private Integer id;
	private Empresa empresa;
	private String idConvenio;
	private String tipoConvenio;
	private Date fechaAnexo;
	private Set anexars = new HashSet(0);

	public Convenio() {
	}

	public Convenio(Empresa empresa, String idConvenio, String tipoConvenio, Date fechaAnexo) {
		this.empresa = empresa;
		this.idConvenio = idConvenio;
		this.tipoConvenio = tipoConvenio;
		this.fechaAnexo = fechaAnexo;
	}

	public Convenio(Empresa empresa, String idConvenio, String tipoConvenio, Date fechaAnexo, Set anexars) {
		this.empresa = empresa;
		this.idConvenio = idConvenio;
		this.tipoConvenio = tipoConvenio;
		this.fechaAnexo = fechaAnexo;
		this.anexars = anexars;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public String getIdConvenio() {
		return this.idConvenio;
	}

	public void setIdConvenio(String idConvenio) {
		this.idConvenio = idConvenio;
	}

	public String getTipoConvenio() {
		return this.tipoConvenio;
	}

	public void setTipoConvenio(String tipoConvenio) {
		this.tipoConvenio = tipoConvenio;
	}

	public Date getFechaAnexo() {
		return this.fechaAnexo;
	}

	public void setFechaAnexo(Date fechaAnexo) {
		this.fechaAnexo = fechaAnexo;
	}

	public Set getAnexars() {
		return this.anexars;
	}

	public void setAnexars(Set anexars) {
		this.anexars = anexars;
	}

}
