package persistencia;
// Generated 9 may. 2022 16:28:04 by Hibernate Tools 5.4.32.Final

import java.util.Date;

/**
 * Convenio generated by hbm2java
 */
public class Convenio implements java.io.Serializable {

	private String idConvenio;
	private Empresa empresa;
	private String tipoConvenio;
	private Date fechaAnexo;

	public Convenio() {
	}

	public Convenio(String idConvenio, Empresa empresa, String tipoConvenio, Date fechaAnexo) {
		this.idConvenio = idConvenio;
		this.empresa = empresa;
		this.tipoConvenio = tipoConvenio;
		this.fechaAnexo = fechaAnexo;
	}

	public String getIdConvenio() {
		return this.idConvenio;
	}

	public void setIdConvenio(String idConvenio) {
		this.idConvenio = idConvenio;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public String getTipoConvenio() {
		return this.tipoConvenio;
	}

	public void setTipoConvenio(String tipoConvenio) {
		this.tipoConvenio = tipoConvenio;
	}

	public Date getFechaAnexo() {
		return this.fechaAnexo;
	}

	public void setFechaAnexo(Date fechaAnexo) {
		this.fechaAnexo = fechaAnexo;
	}

}
