package persistencia;
// Generated 2 may. 2022 16:04:45 by Hibernate Tools 5.4.32.Final

/**
 * Convenio generated by hbm2java
 */
public class Convenio implements java.io.Serializable {

	private String idConvenio;
	private Empresa empresa;
	private String tipoConvenio;

	public Convenio() {
	}

	public Convenio(String idConvenio, Empresa empresa, String tipoConvenio) {
		this.idConvenio = idConvenio;
		this.empresa = empresa;
		this.tipoConvenio = tipoConvenio;
	}

	public String getIdConvenio() {
		return this.idConvenio;
	}

	public void setIdConvenio(String idConvenio) {
		this.idConvenio = idConvenio;
	}

	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public String getTipoConvenio() {
		return this.tipoConvenio;
	}

	public void setTipoConvenio(String tipoConvenio) {
		this.tipoConvenio = tipoConvenio;
	}

}
