package persistencia;
// Generated 28 abr. 2022 15:55:39 by Hibernate Tools 5.4.32.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa implements java.io.Serializable {

	private String cifEmpresa;
	private Poblacion poblacion;
	private String nombreEmpresa;
	private String direccionEmpresa;
	private int telefono1;
	private int telefono2;
	private String emailEmpresa;
	private String faxEmpresa;
	private String paginaWeb;
	private String nombreGerente;
	private String dniGerente;
	private String personaContacto;
	private String cargoContacto;
	private Date fechaActualizacion;
	private boolean organismoPublico;
	private String observaciones;
	private Set convenios = new HashSet(0);
	private Set anexars = new HashSet(0);

	public Empresa() {
	}

	public Empresa(String cifEmpresa, Poblacion poblacion, String nombreEmpresa, String direccionEmpresa, int telefono1,
			int telefono2, String emailEmpresa, String faxEmpresa, String paginaWeb, String nombreGerente,
			String dniGerente, String personaContacto, String cargoContacto, Date fechaActualizacion,
			boolean organismoPublico, String observaciones) {
		this.cifEmpresa = cifEmpresa;
		this.poblacion = poblacion;
		this.nombreEmpresa = nombreEmpresa;
		this.direccionEmpresa = direccionEmpresa;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.emailEmpresa = emailEmpresa;
		this.faxEmpresa = faxEmpresa;
		this.paginaWeb = paginaWeb;
		this.nombreGerente = nombreGerente;
		this.dniGerente = dniGerente;
		this.personaContacto = personaContacto;
		this.cargoContacto = cargoContacto;
		this.fechaActualizacion = fechaActualizacion;
		this.organismoPublico = organismoPublico;
		this.observaciones = observaciones;
	}

	public Empresa(String cifEmpresa, Poblacion poblacion, String nombreEmpresa, String direccionEmpresa, int telefono1,
			int telefono2, String emailEmpresa, String faxEmpresa, String paginaWeb, String nombreGerente,
			String dniGerente, String personaContacto, String cargoContacto, Date fechaActualizacion,
			boolean organismoPublico, String observaciones, Set convenios, Set anexars) {
		this.cifEmpresa = cifEmpresa;
		this.poblacion = poblacion;
		this.nombreEmpresa = nombreEmpresa;
		this.direccionEmpresa = direccionEmpresa;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.emailEmpresa = emailEmpresa;
		this.faxEmpresa = faxEmpresa;
		this.paginaWeb = paginaWeb;
		this.nombreGerente = nombreGerente;
		this.dniGerente = dniGerente;
		this.personaContacto = personaContacto;
		this.cargoContacto = cargoContacto;
		this.fechaActualizacion = fechaActualizacion;
		this.organismoPublico = organismoPublico;
		this.observaciones = observaciones;
		this.convenios = convenios;
		this.anexars = anexars;
	}

	public String getCifEmpresa() {
		return this.cifEmpresa;
	}

	public void setCifEmpresa(String cifEmpresa) {
		this.cifEmpresa = cifEmpresa;
	}

	public Poblacion getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(Poblacion poblacion) {
		this.poblacion = poblacion;
	}

	public String getNombreEmpresa() {
		return this.nombreEmpresa;
	}

	public void setNombreEmpresa(String nombreEmpresa) {
		this.nombreEmpresa = nombreEmpresa;
	}

	public String getDireccionEmpresa() {
		return this.direccionEmpresa;
	}

	public void setDireccionEmpresa(String direccionEmpresa) {
		this.direccionEmpresa = direccionEmpresa;
	}

	public int getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(int telefono1) {
		this.telefono1 = telefono1;
	}

	public int getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(int telefono2) {
		this.telefono2 = telefono2;
	}

	public String getEmailEmpresa() {
		return this.emailEmpresa;
	}

	public void setEmailEmpresa(String emailEmpresa) {
		this.emailEmpresa = emailEmpresa;
	}

	public String getFaxEmpresa() {
		return this.faxEmpresa;
	}

	public void setFaxEmpresa(String faxEmpresa) {
		this.faxEmpresa = faxEmpresa;
	}

	public String getPaginaWeb() {
		return this.paginaWeb;
	}

	public void setPaginaWeb(String paginaWeb) {
		this.paginaWeb = paginaWeb;
	}

	public String getNombreGerente() {
		return this.nombreGerente;
	}

	public void setNombreGerente(String nombreGerente) {
		this.nombreGerente = nombreGerente;
	}

	public String getDniGerente() {
		return this.dniGerente;
	}

	public void setDniGerente(String dniGerente) {
		this.dniGerente = dniGerente;
	}

	public String getPersonaContacto() {
		return this.personaContacto;
	}

	public void setPersonaContacto(String personaContacto) {
		this.personaContacto = personaContacto;
	}

	public String getCargoContacto() {
		return this.cargoContacto;
	}

	public void setCargoContacto(String cargoContacto) {
		this.cargoContacto = cargoContacto;
	}

	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public boolean isOrganismoPublico() {
		return this.organismoPublico;
	}

	public void setOrganismoPublico(boolean organismoPublico) {
		this.organismoPublico = organismoPublico;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Set getConvenios() {
		return this.convenios;
	}

	public void setConvenios(Set convenios) {
		this.convenios = convenios;
	}

	public Set getAnexars() {
		return this.anexars;
	}

	public void setAnexars(Set anexars) {
		this.anexars = anexars;
	}

}
