package persistencia;
// Generated 2 may. 2022 16:04:45 by Hibernate Tools 5.4.32.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Poblacion generated by hbm2java
 */
public class Poblacion implements java.io.Serializable {

	private int codigoPostal;
	private String nombre;
	private String provincia;
	private Set empresas = new HashSet(0);
	private Set datosEfas = new HashSet(0);
	private Set alumnos = new HashSet(0);

	public Poblacion() {
	}

	public Poblacion(int codigoPostal, String nombre, String provincia) {
		this.codigoPostal = codigoPostal;
		this.nombre = nombre;
		this.provincia = provincia;
	}

	public Poblacion(int codigoPostal, String nombre, String provincia, Set empresas, Set datosEfas, Set alumnos) {
		this.codigoPostal = codigoPostal;
		this.nombre = nombre;
		this.provincia = provincia;
		this.empresas = empresas;
		this.datosEfas = datosEfas;
		this.alumnos = alumnos;
	}

	public int getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(int codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public Set getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Set empresas) {
		this.empresas = empresas;
	}

	public Set getDatosEfas() {
		return this.datosEfas;
	}

	public void setDatosEfas(Set datosEfas) {
		this.datosEfas = datosEfas;
	}

	public Set getAlumnos() {
		return this.alumnos;
	}

	public void setAlumnos(Set alumnos) {
		this.alumnos = alumnos;
	}

}
