package persistencia;
// Generated 14 jun. 2022 12:36:32 by Hibernate Tools 5.4.21.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Practica generated by hbm2java
 */
public class Practica implements java.io.Serializable {

	private Integer idPractica;
	private Curso curso;
	private Profesor profesor;
	private String tipoPractica;
	private Date fechaInicio;
	private Date fechaFin;
	private Set anexars = new HashSet(0);

	public Practica() {
	}

	public Practica(Curso curso, Profesor profesor, String tipoPractica, Date fechaInicio, Date fechaFin) {
		this.curso = curso;
		this.profesor = profesor;
		this.tipoPractica = tipoPractica;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
	}

	public Practica(Curso curso, Profesor profesor, String tipoPractica, Date fechaInicio, Date fechaFin, Set anexars) {
		this.curso = curso;
		this.profesor = profesor;
		this.tipoPractica = tipoPractica;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.anexars = anexars;
	}

	public Integer getIdPractica() {
		return this.idPractica;
	}

	public void setIdPractica(Integer idPractica) {
		this.idPractica = idPractica;
	}

	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	public Profesor getProfesor() {
		return this.profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	public String getTipoPractica() {
		return this.tipoPractica;
	}

	public void setTipoPractica(String tipoPractica) {
		this.tipoPractica = tipoPractica;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public Set getAnexars() {
		return this.anexars;
	}

	public void setAnexars(Set anexars) {
		this.anexars = anexars;
	}
	@Override
    public String toString() {
        return "- " + tipoPractica + "   ("+ fechaInicio + " -- " + fechaFin + ") --> "+curso+"\n" ;
    }
}
