package persistencia;
// Generated 9 may. 2022 16:28:04 by Hibernate Tools 5.4.32.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor implements java.io.Serializable {

	private String dniProfesor;
	private String nombre;
	private Set practicas = new HashSet(0);

	public Profesor() {
	}

	public Profesor(String dniProfesor, String nombre) {
		this.dniProfesor = dniProfesor;
		this.nombre = nombre;
	}

	public Profesor(String dniProfesor, String nombre, Set practicas) {
		this.dniProfesor = dniProfesor;
		this.nombre = nombre;
		this.practicas = practicas;
	}

	public String getDniProfesor() {
		return this.dniProfesor;
	}

	public void setDniProfesor(String dniProfesor) {
		this.dniProfesor = dniProfesor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getPracticas() {
		return this.practicas;
	}

	public void setPracticas(Set practicas) {
		this.practicas = practicas;
	}

}
